[private]
@default:
    just --list

# Install the monogram binary
install:
    go install ./cmd/monogram

# Build the go binary
build:
    go build ./cmd/monogram

# Run the functional tests
test: build
    (cd ../.. && python3 runtests.py --tests tests.yaml)
