[private]
default:
    just --list

build: json yaml mermaid dot

mkbuild:
    mkdir -p _build

json: mkbuild
    poetry run python3 xml_to_json.py --input factorial.xml > _build/factorial.json

yaml: mkbuild
    poetry run python3 xml_to_yaml.py --input factorial.xml > _build/factorial.yaml

mermaid: mkbuild
    poetry run python3 xml_to_mermaid.py --input factorial.xml > _build/factorial.mermaid

dot: mkbuild
    poetry run python3 xml_to_dot.py --input factorial.xml > _build/factorial.dot
    dot -Tpng _build/factorial.dot -o _build/factorial.png
